"""Add note, button_show_note to Attendance and create CheckMeal table

Revision ID: 53a829a21165
Revises: 4b0e238ac28b
Create Date: 2024-11-07 23:05:38.401530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a829a21165'
down_revision = '4b0e238ac28b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkmeal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('breakfast', sa.Boolean(), nullable=True),
    sa.Column('breakfast_time', sa.DateTime(), nullable=True),
    sa.Column('lunch', sa.Boolean(), nullable=True),
    sa.Column('lunch_time', sa.DateTime(), nullable=True),
    sa.Column('dinner', sa.Boolean(), nullable=True),
    sa.Column('dinner_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('button_show_note', sa.Boolean(), nullable=True))
        batch_op.drop_column('dinner')
        batch_op.drop_column('breakfast')
        batch_op.drop_column('lunch')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lunch', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('breakfast', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dinner', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('button_show_note')
        batch_op.drop_column('note')

    op.drop_table('checkmeal')
    # ### end Alembic commands ###
