"""Add meal_type column to Attendance

Revision ID: 57e94b6c52bc
Revises: c0b372e54d6d
Create Date: 2024-11-06 00:47:52.966956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e94b6c52bc'
down_revision = 'c0b372e54d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breakfast', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lunch', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dinner', sa.Boolean(), nullable=True))
        batch_op.drop_column('meal_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('dinner')
        batch_op.drop_column('lunch')
        batch_op.drop_column('breakfast')

    # ### end Alembic commands ###
