"""Add attendance_id to CheckMeal

Revision ID: 6aa468426966
Revises: 53a829a21165
Create Date: 2024-11-07 23:29:24.714670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6aa468426966'
down_revision = '53a829a21165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('volunteer')
    op.drop_table('checkmeal')
    op.drop_table('user')
    op.drop_table('attendance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('volunteer_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('check_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('check_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('button_show_note', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], name='attendance_volunteer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='attendance_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.create_table('checkmeal',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('volunteer_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('breakfast', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('breakfast_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lunch', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('lunch_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('dinner', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dinner_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], name='checkmeal_volunteer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='checkmeal_pkey')
    )
    op.create_table('volunteer',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='volunteer_pkey')
    )
    # ### end Alembic commands ###
