"""Add password_hash to User model

Revision ID: 915145be0948
Revises: 57e94b6c52bc
Create Date: 2024-11-06 20:12:37.695943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915145be0948'
down_revision = '57e94b6c52bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=150), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
